Review-Prozess doc hinzugefügt
mi-classroom/mi-web-technologien-beiboot-ss2023-sebastianbroc pull request #1
Opened 2023-05-23 18:39 UTC by sebastianbroc

Bitte einmal um Feedback zu dem erdachten Prozess aus der Markdown-Datei.

2023-05-23 18:52 UTC, finnge requested changes

2023-05-23 18:52 UTC, finnge commented on docs/decisions/0003-review_process.md
> +* Für die neuen Branches werden bei Abschluss eines neuen Meilensteins / einer neuen Funktionalität Pull-Requests auf den main-Branch erstellt
Macht es Sinn nur einen PR für einen Meilenstein anzulegen? Es kann ja sein, dass ein Meilenstein aus mehreren Teilen besteht.

2023-05-24 09:54 UTC, sebastianbroc commented on docs/decisions/0003-review_process.md
> +* Für die neuen Branches werden bei Abschluss eines neuen Meilensteins / einer neuen Funktionalität Pull-Requests auf den main-Branch erstellt
Guter Punkt! Ich glaube, der Begriff "Meilenstein" war etwas Missverständlich. Ich habe dies nun geändert und deutlicher spezifiziert, wie die Größe von Pull-Requests grob zu wählen ist. Ich bin der Meinung, ähnlich zu commit-Größen ist es schwer, eine "goldene Regel" zu finden, und es muss grundsätzlich mit etwas Verstand und Gefühl herangegangen werden.

Dennoch habe ich die "Anatomie eines Perfekten Pull-Request" von Hugo Dias hinzugezogen, um es etwas einzugrenzen.

2023-05-24 09:58 UTC, finnge approved these changes
Sehr gute Idee, dass in einem ADR festzuhalten 🎉

2023-05-24 10:00 UTC, finnge commented
Die Regeln kannst du auch in GitHubs Branch Protection Rule umsetzen

2023-05-24 10:17 UTC, merged